# theme
scheme: Pisces
# scheme: Gemini

# Remove unnecessary files after hexo generate.
minify: true

darkmode: true

# Easily enable fast Ajax navigation on your website.
# For more information: https://github.com/next-theme/pjax
pjax: true

# To generate custom favicons, you can visit Favicon Generator.
# https://realfavicongenerator.net/
favicon:
  small: /favicons/favicon-16x16.png
  medium: /favicons/favicon-32x32.png
  apple_touch_icon: /favicons/apple-touch-icon.png
  safari_pinned_tab: /favicons/safari-pinned-tab.svg
  android_manifest: /favicons/site.webmanifest

# ---------------------------------------------------------------
# Sidebar Settings Start
# ---------------------------------------------------------------
# sidebar:
  # position: left
  # display: post # Show sidebar only in posts which have index.
  #display: always # Show sidebar in all pages.
  # width: 240
  # padding: 18
  # offset: 12

avatar:
  url: /images/avatar.jpg
  rounded: true

social:
  GitHub: https://github.com/xiaweiss || fab fa-github
  E-Mail: mailto:xiaweiss@foxmail.com || fa fa-envelope
  # Weibo: https://weibo.com/xiaweiss || fab fa-weibo

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
# Usage: `Key: /link/ || icon`
# Key is the name of menu item. If translate for this menu will find in languages - this translate will be loaded; if not - Key name will be used. Key is case-senstive.
# Value before `||` delimeter is the target link.
# Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  #tags: /tags/ || fa fa-tags
  #categories: /categories/ || fa fa-th
  # archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

  技术: /categories/技术 || fa fa-cubes
  读书: /categories/读书 || fa fa-book
  #painting: /categories/绘画 || fa fa-paint-brush
  #essay: /categories/随笔 || fa fa-edit

# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false

toc:
  number: false
  # wrap: false

# ---------------------------------------------------------------
# Sidebar Settings End
# ---------------------------------------------------------------

codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: atom-one-light
    dark: atom-one-dark

tag_icon: true

follow_me:
  WeChat: /images/wechat.jpg || fab fa-weixin
  RSS: /atom.xml || fa fa-rss

post_edit:
  enable: false
  url: https://github.com/xiaweiss/xiawei.cc/edit/master/source/

# Comment
disqus:
  enable: true
  shortname: xiawei
  count: true

reading_progress:
  enable: true
  color: "#2ea9df"
  height: 3px

# Follow me on GitHub banner in right-top corner.
github_banner:
  enable: true
  permalink: https://github.com/xiaweiss
  title: Follow me on GitHub

footer:
  since: 2017
  beian:
    enable: true
    icp: 京 ICP 备 17057895 号-2